name: 'proyectouno-recipe'
description: 'Recipe generada automaticamente desde la configuracion exportada.'
type: 'Site'

install:
  - node\n  - field\n  - field_ui\n  - text\n  - views\n  - views_ui\n  - taxonomy\n  - block\n  - image

config:
  import:
    - announcements_feed.settings
    - block.block.claro_breadcrumbs
    - block.block.claro_content
    - block.block.claro_help
    - block.block.claro_help_search
    - block.block.claro_local_actions
    - block.block.claro_messages
    - block.block.claro_page_title
    - block.block.claro_primary_local_tasks
    - block.block.claro_secondary_local_tasks
    - block.block.olivero_account_menu
    - block.block.olivero_breadcrumbs
    - block.block.olivero_content
    - block.block.olivero_help
    - block.block.olivero_main_menu
    - block.block.olivero_messages
    - block.block.olivero_page_title
    - block.block.olivero_powered
    - block.block.olivero_primary_admin_actions
    - block.block.olivero_primary_local_tasks
    - block.block.olivero_search_form_narrow
    - block.block.olivero_search_form_wide
    - block.block.olivero_secondary_local_tasks
    - block.block.olivero_site_branding
    - block_content.type.basic
    - claro.settings
    - comment.settings
    - comment.type.comment
    - core.base_field_override.node.article.promote
    - core.entity_form_display.block_content.basic.default
    - core.entity_form_display.comment.comment.default
    - core.entity_form_display.node.article.default
    - core.entity_form_display.node.content_de_prueba.default
    - core.entity_form_display.node.page.default
    - core.entity_form_display.user.user.default
    - core.entity_form_mode.user.register
    - core.entity_view_display.block_content.basic.default
    - core.entity_view_display.comment.comment.default
    - core.entity_view_display.node.article.default
    - core.entity_view_display.node.article.rss
    - core.entity_view_display.node.article.teaser
    - core.entity_view_display.node.content_de_prueba.default
    - core.entity_view_display.node.content_de_prueba.teaser
    - core.entity_view_display.node.page.default
    - core.entity_view_display.node.page.teaser
    - core.entity_view_display.user.user.compact
    - core.entity_view_display.user.user.default
    - core.entity_view_mode.block_content.full
    - core.entity_view_mode.comment.full
    - core.entity_view_mode.node.full
    - core.entity_view_mode.node.rss
    - core.entity_view_mode.node.search_index
    - core.entity_view_mode.node.search_result
    - core.entity_view_mode.node.teaser
    - core.entity_view_mode.taxonomy_term.full
    - core.entity_view_mode.user.compact
    - core.entity_view_mode.user.full
    - core.menu.static_menu_link_overrides
    - field.field.block_content.basic.body
    - field.field.comment.comment.comment_body
    - field.field.node.article.body
    - field.field.node.article.comment
    - field.field.node.article.field_image
    - field.field.node.article.field_tags
    - field.field.node.content_de_prueba.body
    - field.field.node.content_de_prueba.field_campodos
    - field.field.node.content_de_prueba.field_campotres
    - field.field.node.content_de_prueba.field_campouno
    - field.field.node.page.body
    - field.field.user.user.user_picture
    - field.settings
    - field.storage.block_content.body
    - field.storage.comment.comment_body
    - field.storage.node.body
    - field.storage.node.comment
    - field.storage.node.field_campodos
    - field.storage.node.field_campotres
    - field.storage.node.field_campouno
    - field.storage.node.field_image
    - field.storage.node.field_tags
    - field.storage.user.user_picture
    - field_ui.settings
    - file.settings
    - filter.format.plain_text
    - filter.settings
    - image.settings
    - image.style.large
    - image.style.medium
    - image.style.thumbnail
    - image.style.wide
    - language.content_settings.node.content_de_prueba
    - language.content_settings.path_alias.path_alias
    - language.entity.es
    - language.entity.und
    - language.entity.zxx
    - language.mappings
    - language.negotiation
    - language.types
    - locale.settings
    - menu_ui.settings
    - node.settings
    - node.type.article
    - node.type.content_de_prueba
    - node.type.page
    - olivero.settings
    - search.page.help_search
    - search.page.node_search
    - search.page.user_search
    - system.action.comment_delete_action
    - system.action.comment_publish_action
    - system.action.comment_save_action
    - system.action.comment_unpublish_action
    - system.action.node_delete_action
    - system.action.node_make_sticky_action
    - system.action.node_make_unsticky_action
    - system.action.node_promote_action
    - system.action.node_publish_action
    - system.action.node_save_action
    - system.action.node_unpromote_action
    - system.action.node_unpublish_action
    - system.action.taxonomy_term_publish_action
    - system.action.taxonomy_term_unpublish_action
    - system.action.user_add_role_action.administrator
    - system.action.user_add_role_action.content_editor
    - system.action.user_block_user_action
    - system.action.user_cancel_user_action
    - system.action.user_remove_role_action.administrator
    - system.action.user_remove_role_action.content_editor
    - system.action.user_unblock_user_action
    - system.advisories
    - system.date
    - system.diff
    - system.feature_flags
    - system.image.gd
    - system.image
    - system.mail
    - system.maintenance
    - system.theme.global
    - taxonomy.settings
    - taxonomy.vocabulary.tags
    - text.settings
    - user.flood
    - user.mail
    - user.role.content_editor
    - views.settings
    - views.view.archive
    - views.view.block_content
    - views.view.comment
    - views.view.comments_recent
    - views.view.content
    - views.view.content_recent
    - views.view.files
    - views.view.frontpage
    - views.view.glossary
    - views.view.taxonomy_term
    - views.view.user_admin_people
    - views.view.watchdog
    - views.view.who_s_new
    - views.view.who_s_online
