name: 'proyectouno-recipe'
description: 'Recipe generada automaticamente desde la configuracion exportada.'
type: 'Site'

install:
  - node
  - field
  - field_ui
  - text
  - views
  - views_ui
  - taxonomy
  - block
  - image

config:
  import:
    node:
      - node.type.content_de_prueba
      - node.settings
      - core.entity_form_display.node.content_de_prueba.default
      - core.entity_view_display.node.content_de_prueba.default
      - core.entity_view_display.node.content_de_prueba.teaser
    field:
      - field.field.node.content_de_prueba.body
      - field.field.node.content_de_prueba.field_campodos
      - field.field.node.content_de_prueba.field_campotres
      - field.field.node.content_de_prueba.field_campouno
      - field.storage.node.field_campodos
      - field.storage.node.field_campotres
      - field.storage.node.field_campouno
      - field.storage.node.body
      - field.settings
    language:
      - language.content_settings.node.content_de_prueba
    views:
      - views.view.frontpage
      - views.view.content
      - views.view.taxonomy_term
      - views.settings
    taxonomy:
      - taxonomy.vocabulary.tags
      - taxonomy.settings
    block:
      - block.block.olivero_content
      - block.block.olivero_page_title
      - block.block.olivero_messages
      - block.block.olivero_main_menu
      - block.block.olivero_breadcrumbs
      - block.block.olivero_site_branding
    image:
      - image.style.large
      - image.style.medium
      - image.style.thumbnail
      - image.style.wide
      - image.settings